# Aufgaben zu Unfalltypenkarten und Unfallhäufungsstellen

Versuchen Sie bei den nachfolgenden Aufgaben zu Unfalltypenkarten weitestgehend die Vorgaben der Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV) aus dem “Merkblatt zur Örtlichen Unfalluntersuchung in Unfallkommissionen” (M Uko) umzusetzen.

::: {#exr-unfalltypenkarte}

## Unfalltypenkarten

Erstellen Sie nach den Vorgaben des M Uko eine Unfalltypenkarte für
- eine ausgewählte Autobahn und 
- alle Autobahnen in Gesamtdeutschland

mit 

- `ggplot` und
- `leaflet`

für Unfälle in einem beliebigem Jahr. Welche Darstellungen halten Sie für geeignet?
:::

::: {#exr-unfallhaeufungstellen}
## Unfallhäufungsstellen

Stellen Sie nach den Vorgaben des M Uko Unfallhäufungsstellen in einer Dreijahreskarte in einer beliebigen Stadt dar.
:::

::: {#exr-shiny-karte}
## optional: Interaktive `leaflet`-Karte mit Filtern

Erstellen Sie eine interaktive `leaflet`-Karte der Unfälle in Bochum, beispielsweise mit `shiny` oder `crosstalk`. 
Die Interaktivität soll folgendermaßen gestaltet werden:

- wählbare Unfallkategorien,
- wählbare Unfalltypen,
- wählbare Unfallbeteiligte und
- wählbare Jahre

Zusätzlich soll unter der Karte eine Tabelle mit den gewählten Filtern dargestellt werden.

*Optional* : Ein Download-Button für die gewählten Filtereinstellungen, der eine CSV-Datei erzeugt und herunterlädt.
:::