# Musterlösung Unfalltypenkarte

**Verwendete Pakete laden**

```{{r}}
#| include: false
library(tidyverse)
library(sfnetworks)
library(sf)
library(dplyr)
library(osmdata)
library(leaflet)
library(leaflegend)
library(shiny)
library(igraph)
library(units)
library(tidygraph)
library(dbscan)
library(curl)
```

## Übungsaufgabe 1.1: Unfalltypenkarte

**Daten laden und aufbereiten** 

```{{r}}
file <- list.files("daten/geo", pattern = "^BFStr_Netz.*\\.gpkg$", full.names = TRUE) |> tail(n = 1)

if (length(file) == 0) {
  curl_download(
    "https://www.bast.de/SharedDocs/Daten-TB/Daten-BISStra.zip?__blob=publicationFile&v=5",
    destfile = "daten/Daten-BISStra.zip",
    quiet = FALSE
  )
  unzip("daten/Daten-BISStra.zip", exdir = "daten/geo/")
  file <- list.files("daten/geo", pattern = "^BFStr_Netz.*\\.gpkg$", full.names = TRUE) |> tail(n = 1)
}

d_bfstn <- read_sf(file) |>
  filter(Str_Klasse_kurz == "A" & Sk_Achse == "Bestandsachse") |>
  mutate(rownumber = row_number()) |>
  st_zm()
```

```{{r}}
d_unfaelle_bab_2024 = read_csv2("daten/Unfallorte2024_LinRef.csv") |>
  st_as_sf(coords = c("LINREFX", "LINREFY"), crs = 25832) |>
  st_zm() |>
    mutate(
      abschnitt_id = st_nearest_feature(geometry, d_bfstn),
      distanz = st_distance(geometry, d_bfstn[abschnitt_id, ], by_element = TRUE),
      Str_Kennung = d_bfstn$Str_Kennung[abschnitt_id]
    ) |>
  filter(as.double(distanz) <= 20) |>
  select(UTYP1, UKATEGORIE, Str_Kennung, abschnitt_id)
```

**Grafische Darstellung mit `ggplot`**

```{{r}}
farben_utyp <- c(
"1" = "green",
"2" = "yellow",
"3" = "red",
"4" = "lightgrey",
"5" = "blue",
"6" = "orange",
"7" = "black"
)
```

```{{r}}
formen_ukat <- c(
  "1" = 15,
  "2" = 16,
  "3" = 17
)
```

**Grafische Darstellung von Unfällen auf der Beispielautobahn A40 mit ggplot**

```{{r}}
d_staedte <- st_as_sf(
  tibble::tribble(
    ~ stadt, ~lat, ~lon,
    "Dortmund", 51.5142, 7.4684,
    "Duisburg", 51.4351, 6.7627,
    "Venlo", 51.37, 6.1681
  ),
  coords = c("lon", "lat"),
  crs = 4326
) |>
  st_transform(25832)
  
ggplot () +
  geom_sf(data = filter(d_bfstn, Str_Kennung == "A40"), colour = "grey", size = 0.4) +
  geom_sf(data = d_staedte, colour = "red", shape = 22) +
  geom_sf_text(data = d_staedte, aes(label = stadt), nudge_y = 5000, size = 3) +
  geom_sf(
    data = filter(d_unfaelle_bab_2024, Str_Kennung == "A40"),
    mapping = aes(
      group = UTYP1,
      colour = as.character(UTYP1), 
      shape = as.character(UKATEGORIE)),
    size = 1.5) +
  scale_colour_manual(name = "Unfalltyp", values = farben_utyp, labels = c("Fahrunfall","Abbiege-Unfall", "Einbiegen/Kreuzen-Unfall", "Überschreiten-Unfall","Unfall durch ruhenden Verkehr", "Unfall im Längsverkehr", "Sonstiger Unfall")) +
  scale_shape_manual(name = "Unfallschwere", values = formen_ukat, labels = c("Unfall mit Getöteten", "Unfall mit Schwerverletzten", "Unfall mit Leichtverletzten")) +
  labs(title = "Unfalltypenkarte der A40 im Jahr 2024") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title = element_blank(),
    axis.text  = element_blank(),
    axis.ticks = element_blank()
  )
```

**Grafische Darstellung aller Unfälle auf Bundesautobahnen mit ggplot**

```{{r}}
d_staedte2 <- st_as_sf(
  tibble::tribble(
    ~ stadt, ~lat, ~lon,
    "Berlin", 52.5244, 13.4105,
    "Hamburg", 53.5511, 9.9937,
    "München", 48.1372, 11.5761,
    "Köln", 50.9352, 6.9531
  ),
  coords = c("lon", "lat"),
  crs = 4326
) |>
  st_transform(25832)
  
ggplot () +
  geom_sf(data = d_bfstn, colour = "grey", size = 0.4) +
  geom_sf(data = d_staedte2, colour = "red", shape = 22) +
  geom_sf_text(data = d_staedte2, aes(label = stadt), nudge_y = 5000, size = 3) +
  geom_sf(
    data = d_unfaelle_bab_2024,
    mapping = aes(
      group = UTYP1,
      colour = as.character(UTYP1), 
      shape = as.character(UKATEGORIE)),
    size = 0.5) +
  scale_colour_manual(name = "Unfalltyp", values = farben_utyp, labels = c("Fahrunfall","Abbiege-Unfall", "Einbiegen/Kreuzen-Unfall", "Überschreiten-Unfall","Unfall durch ruhenden Verkehr", "Unfall im Längsverkehr", "Sonstiger Unfall")) +
  scale_shape_manual(name = "Unfallschwere", values = formen_ukat, labels = c("Unfall mit Getöteten", "Unfall mit Schwerverletzten", "Unfall mit Leichtverletzten")) +
  labs(title = "Unfalltypenkarte aller deutschen Autobahnen im Jahr 2024") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
    axis.title = element_blank(),
    axis.text  = element_blank(),
    axis.ticks = element_blank()
  )
```

**Grafische Darstellung mit `leaflet`**

```{{r}}
farben_utyp_leaf <- colorFactor(unname(farben_utyp), domain = 1:7)
```

**Grafische Darstellung von Unfällen auf der Beispielautobahn A40 mit leaflet**

```{{r}}
leaflet(data = d_unfaelle_bab_2024 |> filter(Str_Kennung == "A40") |> st_transform(crs = 4326)) |>   
  addProviderTiles(providers$Stadia.AlidadeSmooth) |>
  addCircleMarkers(
    radius = ~c(12, 8, 5)[UKATEGORIE],
    color = ~farben_utyp_leaf(UTYP1), opacity = 1,
    fillColor = ~farben_utyp_leaf(UTYP1), fillOpacity = 0.9,
    popup = ~paste("Unfallkategorie:", UKATEGORIE, "<br>Unfalltyp:", UTYP1)
  ) |>
  addLegend(
    position = "bottomright",
    colors = c("green", "yellow",  "red", "lightgrey", "blue", "orange", "black"), labels = c("Fahrunfall","Abbiege-Unfall",
    "Einbiegen/Kreuzen-Unfall", "Überschreiten-Unfall","Unfall durch ruhenden Verkehr", "Unfall im Längsverkehr", 
    "Sonstiger Unfall"),
    title = "Unfalltyp",
    opacity = 1
  ) |>
  addLegendSize(
    values = c(12, 8, 5),
    breaks = c("Unfall mit Getöteten" = 12, "Unfall mit Schwerverletzten" = 8, "Unfall mit Leichtverletzten" = 5),
    color = "black", 
    fillColor = "black", 
    fillOpacity = 0.9,
    shape = "circle",
    position = "bottomleft",
    title = "Unfallschwere"
  )
```

**Grafische Darstellung aller Unfälle auf Bundesautobahnen mit leaflet**

```{{r}}
leaflet(data = st_transform(d_unfaelle_bab_2024, 4326)) |>   
  addProviderTiles(providers$Stadia.AlidadeSmooth) |>
  addCircleMarkers(
    radius = ~c(12, 8, 5)[UKATEGORIE],
    color = ~farben_utyp_leaf(UTYP1), opacity = 1,
    fillColor = ~farben_utyp_leaf(UTYP1), fillOpacity = 0.9,
    popup = ~paste("Unfallkategorie:", UKATEGORIE, "<br>Unfalltyp:", UTYP1, "<br>Autobahn:", Str_Kennung)
  ) |>
  addLegend(
    position = "bottomright",
    colors = c("green", "yellow",  "red", "lightgrey", "blue", "orange", "black"), labels = c("Fahrunfall","Abbiege-Unfall",
    "Einbiegen/Kreuzen-Unfall", "Überschreiten-Unfall","Unfall durch ruhenden Verkehr", "Unfall im Längsverkehr", 
    "Sonstiger Unfall"),
    title = "Unfalltyp",
    opacity = 1
  ) |>
  addLegendSize(
    values = c(12, 8, 5),
    breaks = c("Unfall mit Getöteten" = 12, "Unfall mit Schwerverletzten" = 8, "Unfall mit Leichtverletzten" = 5),
    color = "black", 
    fillColor = "black", 
    fillOpacity = 0.9,
    shape = "circle",
    position = "bottomleft",
    title = "Unfallschwere"
  )
```

## Übungsaufgabe 1.2 : Unfallhäufungsstellen

**Daten einlesen und aufbereiten**

```{{r}}
d_unfaelle_bochum_3j <- bind_rows(
  read_csv2("daten/Unfallorte2024_LinRef.csv") |> mutate(jahr = 2024),
  read_csv2("daten/Unfallorte2023_LinRef.csv") |> mutate(jahr = 2023),
  read_csv2("daten/Unfallorte2022_LinRef.csv") |> mutate(jahr = 2022),
  ) |>
  filter(
    ULAND == "05",
    UREGBEZ == "9",
    UKREIS == "11",
    UGEMEINDE == "000"
  ) |>
  st_as_sf(coords = c("LINREFX", "LINREFY"), crs = 25832) |>
  st_zm()  |>
  mutate(
    abschnitt_id_bab = st_nearest_feature(geometry, d_bfstn),
    distanz_bab = st_distance(geometry, d_bfstn[abschnitt_id_bab, ], by_element = TRUE),
    name_bab = d_bfstn$Str_Kennung[abschnitt_id_bab]
  ) |>
  filter(as.double(distanz_bab) > 20) |>
  select(OID_, UJAHR, UMONAT, USTUNDE, UKATEGORIE, UTYP1,
         IstPKW, IstRad, IstFuss, IstKrad,
         ULICHTVERH, IstStrassenzustand)
```

```{{r}}
d_bochum_stadtgebiet <- st_read("daten/geo/Stadtgrenze.shp") |>
  st_transform(25832)
```

**Knoten-Kanten-Modell**

```{{r}}
if (!file.exists("daten/strassen_bo.RData")) {
  d_strassen <- opq(bbox = "Bochum, Germany") |>
    add_osm_feature(
      key = "highway",
      value = c(
        "trunk", "trunk_link",
        "primary", "primary_link",
        "secondary", "secondary_link",
        "tertiary", "tertiary_link",
        "residential", "unclassified"
      )
    ) |>
    osmdata_sf()
  save(d_strassen, file = "daten/strassen_bo.RData")
} else {
  load(file = "daten/strassen_bo.RData")
}
```

```{{r}}
d_kanten <- d_strassen$osm_lines |>
  select(name, highway, geometry) |>
  st_transform(25832)
```

```{{r}}
d_netz <- as_sfnetwork(d_kanten, directed = FALSE) |>
  convert(to_spatial_smooth)
```

```{{r}}
d_netz <- local({
  knoten_sf <- d_netz |> activate("nodes") |> st_as_sf()
  nachbarn <- st_is_within_distance(knoten_sf, dist = set_units(20, "m"))
  gruppen <- components(graph_from_adj_list(nachbarn, mode = "all"))$membership
  d_netz |>
    activate("nodes") |>
    mutate(group = gruppen) |>
    convert(to_spatial_contracted, group, simplify = TRUE)
})
```

```{{r}}
d_netz <- d_netz |>
  activate("edges") |>
  arrange(edge_length()) |>
  filter(!edge_is_multiple(), !edge_is_loop())
```

```{{r}}
d_knoten <- d_netz |> activate("nodes") |> st_as_sf() |> st_filter(d_bochum_stadtgebiet)
d_kanten <- d_netz |> activate("edges") |> st_as_sf() |> st_filter(d_bochum_stadtgebiet)
```

**Ermittlung von Unfallhäufungsstellen**

```{{r}}
d_unfaelle_bochum_3j <- d_unfaelle_bochum_3j |>
  mutate(
    knoten_id = st_nearest_feature(geometry, d_knoten),
    distanz_knoten = as.numeric(st_distance(geometry, d_knoten[knoten_id, ], by_element = TRUE))
  ) 
```

**Unfallhäufungsstellen an Knotenpunkten**

```{{r}}
d_knoten_uhs <- d_knoten |>
  mutate(knoten_id = row_number()) |>
  inner_join(
    d_unfaelle_bochum_3j |>
      st_drop_geometry() |>
      filter(distanz_knoten <= 50) |>
      count(knoten_id, name = "anzahl_unfaelle") |>
      filter(anzahl_unfaelle >= 5),
    by = "knoten_id"
  )
```

**Unfallhäufungsstellen an freien Strecken**

```{{r}}
d_strecke_uhs <- NULL

d_unfaelle_strecke <- d_unfaelle_bochum_3j |>
  filter(distanz_knoten > 50)

if (nrow(d_unfaelle_strecke) > 0) {
  d_unfaelle_strecke$n_nearby <- lengths(
    st_intersects(st_buffer(d_unfaelle_strecke, 50), d_unfaelle_strecke)
  )

  d_uhl_kandidaten <- d_unfaelle_strecke |>
    filter(n_nearby >= 5)

  if (nrow(d_uhl_kandidaten) > 0) {
    d_uhl_kandidaten$cluster <- dbscan(st_coordinates(d_uhl_kandidaten), eps = 50, minPts = 5)$cluster

    d_strecke_uhs <- d_uhl_kandidaten |>
      filter(cluster > 0) |>
      group_by(cluster) |>
      summarise(
        anzahl_unfaelle = n(),
        geometry = st_centroid(st_combine(geometry)),
        .groups = "drop"
      )
  }
}

```

**Grafische Darstellung der Unfallhäufungsstellen auf Stadtstraßen in Bochum**

```{{r}}
karte <- leaflet() |>
  addProviderTiles(providers$Stadia.AlidadeSmooth) |>
  addPolylines(
    data = st_transform(d_kanten, 4326),
    color = "black", weight = 1, opacity = 1,
    group = "Straßennetz"
  ) |>
  addCircles(
    data = st_transform(d_knoten_uhs, 4326),
    radius = 50,
    fillOpacity = 0.4,
    color = "purple", weight = 2,
    popup = ~paste("UHS an Knotenpunkt<br>Anzahl Unfälle:", anzahl_unfaelle),
    group = "UHS an Knotenpunkten"
  ) |>
  addAwesomeMarkers(
    data = st_transform(d_knoten_uhs, 4326),
    icon = awesomeIcons(icon = "alert-circled", library = "ion", markerColor = "purple", iconColor = "black"),
    group = "UHS an Knotenpunkten"
  ) |>
  addCircleMarkers(
    data = st_transform(st_jitter(d_unfaelle_bochum_3j, amount = 3), 4326),
    radius = 3,
    color = ~farben_utyp_leaf(UTYP1), opacity = 0.7,
    fillColor = ~farben_utyp_leaf(UTYP1), fillOpacity = 0.7,
    popup = ~paste0(
      "Unfall im ",
      month(as.numeric(UMONAT), label = TRUE, abbr = FALSE), " ", UJAHR,
      " um ", USTUNDE, " Uhr<br>",
      "Typ: ", UTYP1, " | Kategorie: ", UKATEGORIE
    ),
    group = "Unfälle"
  )

if (!is.null(d_strecke_uhs) && nrow(d_strecke_uhs) > 0) {
  karte <- karte |>
    addCircles(
      data = st_transform(d_strecke_uhs, 4326),
      radius = 50,
      fillOpacity = 0.4,
      color = "pink", weight = 2,
      popup = ~paste("UHS an freier Strecke<br>Anzahl Unfälle:", anzahl_unfaelle),
      group = "UHS an freier Strecke"
    ) |>
    addAwesomeMarkers(
      data = st_transform(d_strecke_uhs, 4326),
      icon = awesomeIcons(icon = "alert-circled", library = "ion", markerColor = "pink", iconColor = "black"),
      group = "UHS an freier Strecke"
    )
}

karte |>
  addLegend(
    position = "bottomleft",
    colors = c("purple", "pink"),
    labels = c("UHS an Knotenpunkten (≥ 5 Unfälle)", "UHS an freier Strecke (≥ 5 Unfälle)"),
    title = "Unfallhäufungsstellen",
    opacity = 1
  ) |>
  addLegend(
    position = "bottomright",
    colors = c("green", "yellow", "red", "lightgrey", "blue", "orange", "black"),
    labels = c("Fahrunfall", "Abbiege-Unfall", "Einbiegen/Kreuzen-Unfall", "Überschreiten-Unfall", "Unfall durch ruhenden Verkehr", "Unfall im Längsverkehr", "Sonstiger Unfall"),
    title = "Unfalltyp",
    opacity = 1
  ) |>
  addLayersControl(
    overlayGroups = c("Straßennetz", "UHS an Knotenpunkten", "UHS an freier Strecke", "Unfälle"),
    options = layersControlOptions(collapsed = FALSE)
  )
```

## Optionale Aufgabe 

Siehe die Kapitel *Code zur interaktiven Karte der Verkehrsunfälle in Bochum* und *Interaktive Karte der Verkehrsunfälle in Bochum* sowie die Datei `unfaelle_shiny.qmd`  

