---
title: "Aufgaben zu Unfalltypenkarten"
format: html
---

Versuchen Sie bei den nachfolgenden Aufgaben zu Unfalltypenkarten weitestgehend die Vorgaben der Forschungsgesellschaft für Straßen- und
Verkehrswesen (FGSV) aus dem “Merkblatt zur Örtlichen Unfalluntersuchung in Unfallkommissionen” (M Uko) umzusetzen.

## Aufgabe 1 : Unfalltypenkarten

a. Erstellen Sie nach den Vorgaben des M Uko 
- [ ] eine Unfalltypenkarte für eine ausgewählte Autobahn und 
- [ ] eine Unfalltypenkarte für Gesamtdeutschland

    mit `ggplot` für Unfälle in einem beliebigem Jahr.

[]{.down60}

b. Erstellen Sie nach den Vorgaben des M Uko 
- [ ] eine Unfalltypenkarte für eine ausgewählte Autobahn und 
- [ ] eine Unfalltypenkarte für Gesamtdeutschland

    mit `leaflet` für Unfälle in einem beliebigem Jahr.


## Aufgabe 2 : Unfallhäufungsstellen

- [ ] Überprüfen Sie nach den Vorgaben des M Uko Unfallhäufungsstellen in einer beliebigen Stadt.

## Optionale Aufgabe: Interaktive `leaflet`-Karte mit `Shiny`

Erstellen Sie eine interaktive `leaflet`-Karte der Unfälle in Bochum in `Shiny`. 
Die Interaktivität soll folgendermaßen gestaltet werden:

- [ ]  Wählbare Unfallkategorien
- [ ]  Wählbare Unfalltypen
- [ ]  Wählbare Verkehrsbeteiligte
- [ ]  Wählbare Jahre

Zusätzlich soll unter der Karte eine Tabelle mit den gewählten Filtern dargestellt werden.

*Optional* : Ein Download-Button für die gewählten Filtereinstellungen, der eine CSV-Datei erzeugt und herunterlädt.